In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Customer_project/final_02_comp.csv")

print(df.columns)

Index(['Complaint', 'Product', 'Complaint_Length', 'Processed_Complaint'], dtype='object')

In [ ]:
df.head()

,Complaint,Product,Complaint_Length,Processed_Complaint
0,Received Capital One charge card offer XXXX. A...,Credit card,714,received capital one charge card offer applied...
1,I do n't know how they got my cell number. I t...,Debt collection,52,nt know got cell number told would deal onlybw...
2,I 'm a longtime member of Charter One Bank/RBS...,Credit card,692,longtime member charter one bankrbs citizen ba...
3,"After looking at my credit report, I saw a col...",Credit reporting,84,looking credit report saw collection account b...
4,I received a call from a XXXX XXXX from XXXX @...,Debt collection,140,received call ext stating owed wanted however ...

In [ ]:
import pandas as pd
import numpy as np
import joblib

from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.sequence import pad_sequences

from transformers import (
    DistilBertTokenizerFast,
    DistilBertForSequenceClassification
)

import torch

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

In [ ]:
PROJECT_PATH = "/content/drive/MyDrive/Customer_project"

In [ ]:
df = pd.read_csv(f"{PROJECT_PATH}/final_02_comp.csv")

print(df.shape)

df.head()

(112503, 4)

,Complaint,Product,Complaint_Length,Processed_Complaint
0,Received Capital One charge card offer XXXX. A...,Credit card,714,received capital one charge card offer applied...
1,I do n't know how they got my cell number. I t...,Debt collection,52,nt know got cell number told would deal onlybw...
2,I 'm a longtime member of Charter One Bank/RBS...,Credit card,692,longtime member charter one bankrbs citizen ba...
3,"After looking at my credit report, I saw a col...",Credit reporting,84,looking credit report saw collection account b...
4,I received a call from a XXXX XXXX from XXXX @...,Debt collection,140,received call ext stating owed wanted however ...

In [ ]:
X = df["Processed_Complaint"]

y = df["Product"]

In [ ]:
label_encoder = joblib.load(
    "/content/drive/MyDrive/Customer_project/models/label_encoder.pkl"
)

In [ ]:
y_encoded = label_encoder.transform(y)

print("Classes")

print(label_encoder.classes_)

Classes
['Bank account or service' 'Consumer Loan' 'Credit card'
 'Credit reporting' 'Debt collection' 'Money transfers' 'Mortgage'
 'Payday loan' 'Prepaid card' 'Student loan']

In [ ]:
bow_vectorizer = joblib.load(
    "/content/drive/MyDrive/Customer_project/models/bow_vectorizer.pkl"
)

tfidf_vectorizer = joblib.load(
    "/content/drive/MyDrive/Customer_project/models/tfidf_vectorizer.pkl"
)

lstm_tokenizer = joblib.load(
    "/content/drive/MyDrive/Customer_project/models/lstm_tokenizer.pkl"
)